---
# tasks file for common
- name: Install required base packages
  apt: name={{ item }} state=present
  with_items:
    - sudo
    - curl
    - git
    - python-mysqldb
    - zip
    - unzip
    - libyaml-dev
    - pip
  become: yes