- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define common_packages.
  set_fact:
    common_packages: "{{ __common_packages | list }}"
  when: common_packages is not defined

- name: Define common_users.
  set_fact:
    common_users: "{{ __common_users | list }}"
  when: common_users is not defined

- name: Define common_groups.
  set_fact:
    common_groups: "{{ __common_groups | list }}"
  when: common_groups is not defined